const ListsCreated = {"Authors" : [
  "Borges.jpg",
  "Dostoyevsky - Translations Comparison.jpg",
  "Julius Evola.jpg",
  "Lovecraft.png",
  "Nick Land.png",
  "Nietzsche - 1.png",
  "Nietzsche - 2.png",
  "Rene Guenon.png",
  "Ted Kaczynski.png",
  "Zizek - 1.jpg",
  "Zizek - 2.png"
],
"Canon" : [
  "St Johns College Great Books List.png",
  "The Lit Canon.jpg"
],
"Charts on Intellectual property" : [
  "Bioshock Infinite.jpg",
  "Conan The Barbarian.jpg",
  "Discworld.jpg",
  "Evangelion Further Reading.png",
  "Warhammer 40k - 1.jpg",
  "Warhammer 40k - 2.jpg"
],
"Conspiracy" : [
  "Gatekeepers Remorse.jpg",
  "pizzagate1.jpg",
  "pizzagate2.jpg",
  "Textbooks Of The Elite.png",
  "x.jpg"
],
"Country & Region" : [
  "Brazil - Comtemporanea.png",
  "Brazil - Modernista.png",
  "Brazil - Pos Romanticos.png",
  "Canada - Authors.png",
  "Canada - Poetry.png",
  "China.jpg",
  "France - Forgotten.jpg",
  "France - Renaissance.png",
  "India.jpg",
  "Iran.png",
  "Irish.png",
  "Italy -Renaissance Literature.png",
  "Italy.jpg",
  "Korean.jpg",
  "Latin America.png",
  "Norway.png",
  "Poland.png",
  "Serbia.png",
  "Spain - Mystic.png",
  "Spain.png"
],
"History, Geography & Antropology" : [
  "Bronze Age.jpg",
  "Greeks - 1.jpg",
  "Greeks - 2.jpg",
  "Greeks - 3.jpg",
  "Indo Europeans.jpg",
  "Romans - 1.jpg",
  "Romans - 2.jpg",
  "Romans - 4.jpg"
],
"Horror, Creepy & Disturbing" : [
  "Dark and Disturbing Literature.jpg",
  "Gothic and Horror Flowchart.jpg",
  "Horror Fiction.jpg",
  "Horror Story Collections.png",
  "Weird Stories.png"
],
"Kommando" : [
  "Fitchart.jpg",
  "Kommando.png",
  "Victory Now.jpg",
  "War Literature.jpg"
],
"Literature" : [
  "Cyberpunk.png",
  "Fantasy.jpg",
  "National Epics.png",
  "SciFi.jpg",
  "Short Story.jpg",
  "Web Novels.jpg",
  "Western Theatre.png"
],
"Poetry" : [
  "Lit Favorite Poets.png",
  "Poems on Massacres and Hell.jpg",
  "Poetry - Meme Edition.jpg"
],
"Politics & Philosophy" : [
  "4chan Pol - 1.jpg",
  "4chan Pol - 2.jpg",
  "British Conservatism.jpg",
  "Communalism.png",
  "Distributism.jpg",
  "EcoFascism.png",
  "Facism.jpg",
  "Leftist & Progressive.jpg",
  "Legal Philosophy Guide.png",
  "Monarchia.jpg",
  "National Communism.jpg",
  "Neoliberal.png",
  "Political Philosophy - 1.jpg",
  "Political Philosophy - 2.jpg",
  "Right Wing Socialism.png",
  "Slave Lord Guide.jpg"
],
"Religion" : [
  "Bibles Translations.png",
  "Buddhism 1.jpg",
  "Buddhism 2.jpg",
  "Celtic Paganism.png",
  "Christianity - Ecotheology.jpg",
  "Christianity - Mysticism.jpg",
  "Christianity - Orthodox 1.jpg",
  "Christianity - Orthodox 2 PLUS SCHIZO STUFF.png",
  "Christianity.png",
  "Daoism.jpg",
  "Esoterica.jpg",
  "German Paganism.png",
  "Hermeticism.jpg",
  "Hindu Texts.png",
  "Initiation into Hermetics.png",
  "Islam.jpg",
  "Medieval Mysticism.png",
  "Quran Translations.jpg",
  "Satanism.png",
  "Western Occultism - 1.png",
  "Western Occultism - 2.png",
  "World Religions Chart.jpg"
],
"Science" : [
  "Computer Science.jpg",
  "Math - 1.jpg",
  "Math - 2.png",
  "Math - 3.jpg",
  "Math - 4.jpg",
  "Math - 4.png",
  "Trivium.png"
],
"Themed Charts" : [
  "Burgerpunk.png",
  "Drooger.png",
  "Great Characters.jpg",
  "Lain Pill.jpg",
  "Middle Earth.jpg",
  "Orange Pill - Bitcoin.jpg",
  "Outdoors.png",
  "Paranoia.png",
  "Patrician Kid.png",
  "Pewdiepie Reading List.jpg"
],
"Tops" : [
  "Lit Top 100 Books 2018.jpg",
  "Lit Top 100 Books 2019.jpg",
  "Lit Top 100 Books 2020.jpg",
  "Lit Top 100 Novels 2020.jpg",
  "Portuguese Language Top 50.png"
]};