const ListsCreated = {"Authors" : [
  "Borges.jpg",
  "Dante Translations.jpg",
  "Dostoyevsky - Translations Comparison.jpg",
  "Julius Evola.jpg",
  "Kant.png",
  "Lovecraft.png",
  "Malazan.jpg",
  "Nick Land.png",
  "Nietzsche - 1.png",
  "Nietzsche - 2.png",
  "Plato.png",
  "Rene Guenon.png",
  "Seraphim Rose.png",
  "Ted Kaczynski.png",
  "Zizek - 1.jpg",
  "Zizek - 2.png"
],
"Canon" : [
  "St Johns College Great Books List.png",
  "The Lit Canon - 1.jpg",
  "The Lit Canon - 2.jpg"
],
"Charts on Intellectual property" : [
  "Banepill.jpg",
  "Baudrillard.png",
  "Bioshock Infinite.jpg",
  "Conan The Barbarian.jpg",
  "Cosmere Reading Order.png",
  "Discworld.jpg",
  "Evangelion Further Reading.png",
  "Lain Pill.jpg",
  "Snufkin Pill.png",
  "The Big Lez.png",
  "Warhammer 40k - 1.jpg",
  "Warhammer 40k - 2.jpg"
],
"Conspiracy" : [
  "Gatekeepers Remorse.jpg",
  "Green Pill Chart.jpg",
  "pizzagate1.jpg",
  "pizzagate2.jpg",
  "Textbooks Of The Elite.png",
  "x.jpg"
],
"Country & Region" : [
  "Brazil - Comtemporanea.png",
  "Brazil - Modernista.png",
  "Brazil - Pos Romanticos.png",
  "Canada - Authors.png",
  "Canada - Poetry.png",
  "China.jpg",
  "France - Forgotten.jpg",
  "France - Renaissance.png",
  "India.jpg",
  "Iran.png",
  "Irish.png",
  "Italy -Renaissance Literature.png",
  "Italy.jpg",
  "Korean.jpg",
  "Latin America.png",
  "Norway.png",
  "Persia.jpg",
  "Poland.png",
  "Serbia.png",
  "Spain - Mystic.png",
  "Spain.png",
  "United States (Babylon).jpg"
],
"History, Geography & Antropology" : [
  "Bronze Age.jpg",
  "Greeks - 1.jpg",
  "Greeks - 2.jpg",
  "Greeks - 3.jpg",
  "Indo Europeans.jpg",
  "Romans - 1.jpg",
  "Romans - 2.jpg",
  "Romans - 4.jpg"
],
"Horror, Creepy & Disturbing" : [
  "Dark and Disturbing Literature.jpg",
  "Gothic and Horror Flowchart.jpg",
  "Horror Fiction.jpg",
  "Horror Story Collections.png",
  "Post Apocalyptic.jpg",
  "Weird Stories.png"
],
"K Related & Self Improvment" : [
  "Drawing Guide.jpg",
  "Fitchart.jpg",
  "Kommando.png",
  "Prep.jpg",
  "Victory Now.jpg",
  "War Literature.jpg"
],
"Literature" : [
  "Cyberpunk.png",
  "Fantasy.jpg",
  "Guide to Western Literature.jpg",
  "High Romance.png",
  "National Epics.png",
  "SciFi & Fantasy.png",
  "SciFi - 1.jpg",
  "SciFi - 2.jpg",
  "Short Story - 1.jpg",
  "Short Story - 2.jpg",
  "Web Novels.jpg",
  "Western Theatre.png"
],
"Miscellaneous Knowledge  Fields" : [
  "Biology.png",
  "Computer Science.jpg",
  "Learning to invest.png",
  "Math - 1.jpg",
  "Math - 2.png",
  "Math - 3.jpg",
  "Math - 4.jpg",
  "Math - 4.png",
  "Psychotherapy.png",
  "Trivium.png"
],
"Poetry" : [
  "English Poetry Guide.png",
  "Introduction to Verse.jpg",
  "Lit Favorite Poets - 1.png",
  "Lit Favorite Poets - 2.png",
  "Poems on Massacres and Hell.jpg",
  "Poetry - Meme Edition.jpg"
],
"Politics, Philosophy & Economics" : [
  "4chan Pol - 1.jpg",
  "4chan Pol - 2.jpg",
  "Analytic Phil - 1.jpg",
  "Analytic Philosophy - 1.png",
  "Analytic Philosophy - 2.jpg",
  "Anti Work Reading List.png",
  "British Conservatism.jpg",
  "Communalism.png",
  "Deep Ecology.jpg",
  "Distributism.jpg",
  "EcoFascism.png",
  "Economics Education.png",
  "Facism.jpg",
  "Leftist & Progressive.jpg",
  "Leftist Theory Starter Options.jpg",
  "Legal Philosophy Guide.png",
  "Libertarian.jpg",
  "Monarchia.jpg",
  "National Communism.jpg",
  "Neoliberal.png",
  "Philosophy Overview.jpg",
  "Philosophystack.png",
  "Political Philosophy - 1.jpg",
  "Political Philosophy - 2.jpg",
  "Rhetoric.jpg",
  "Right Wing Literature.jpg",
  "Right Wing Socialism.png",
  "Slave Lord Guide.jpg",
  "Stoicism.jpg",
  "Traditionalism.jpg"
],
"Religion" : [
  "Bibles Translations.png",
  "Buddhism 1.jpg",
  "Buddhism 2.jpg",
  "Buddhism 3.jpg",
  "Celtic Paganism.png",
  "Christianity - Breadpill.png",
  "Christianity - Ecotheology.jpg",
  "Christianity - Mysticism.jpg",
  "Christianity - Orthodox 1.jpg",
  "Christianity - Orthodox 2 PLUS SCHIZO STUFF.png",
  "Christianity.png",
  "Daoism.jpg",
  "Esoterica.jpg",
  "German Paganism.png",
  "Hermeticism.jpg",
  "Hindu Texts.png",
  "Initiation into Hermetics.png",
  "Islam - 1.jpg",
  "Islam - 2.png",
  "Medieval Mysticism.png",
  "Quran Translations.jpg",
  "Satanism.png",
  "Western Occultism - 1.png",
  "Western Occultism - 2.png",
  "World Religions Chart.jpg"
],
"Themed Charts" : [
  "Blackpilled.png",
  "Books About Books.png",
  "Burgerpunk - General.png",
  "Burgerpunk - Value Menu.png",
  "By Age - Books for Teenage Boys.png",
  "By Age - Patrician Child.png",
  "Depressing Literature.jpg",
  "Doomer.jpg",
  "Drooger.png",
  "Dying Earth Core.png",
  "Female - Authors 1.jpg",
  "Female - Authors 2.png",
  "Female - Understanding Women.png",
  "Film Theory.png",
  "Golden Pill.jpg",
  "Great Characters.jpg",
  "Middle Earth.jpg",
  "Nautical.png",
  "Orange Pill - Bitcoin.jpg",
  "Outdoors.png",
  "Paranoia.png",
  "Pewdiepie Reading List.jpg",
  "Self Published.jpg",
  "Tiger Literature.jpg",
  "Twitter Core.jpg",
  "Utopianism.jpg"
],
"Tops" : [
  "Lit Top 100 Books 2018.jpg",
  "Lit Top 100 Books 2019.jpg",
  "Lit Top 100 Books 2020.jpg",
  "Lit Top 100 Books 2021.png",
  "Lit Top 100 Novels 2020.jpg",
  "Lit top 2014 to 2020 avarege.jpeg",
  "Portuguese Language Top 50.png"
]};