const ListsCreated = {"Authors" : [
  "Albert Kamus.jpg",
  "Borges.jpg",
  "Dante Translations.jpg",
  "Dostoyevsky - Translations Comparison.jpg",
  "Jonathan Bowden.jpg",
  "Julius Evola 1.jpg",
  "Julius Evola 2.jpg",
  "Kant.png",
  "Lovecraft.png",
  "Malazan.jpg",
  "Nick Land.png",
  "Nietzsche - 1.png",
  "Nietzsche - 2.png",
  "Nietzsche - 3.jpg",
  "Plato.png",
  "Rene Guenon.png",
  "Seraphim Rose.png",
  "Ted Kaczynski.png",
  "Willian Shakespeare.png",
  "Zizek - 1.jpg",
  "Zizek - 2.png",
  "Zizek - 3.jpg"
],
"Canon" : [
  "St Johns College Great Books List.png",
  "The Lit Canon - 1.jpg",
  "The Lit Canon - 2.jpg"
],
"Charts on Intellectual property" : [
  "Banepill.jpg",
  "Baudrillard.png",
  "Bioshock Infinite.jpg",
  "Books inside other Media.png",
  "Conan The Barbarian.jpg",
  "Cosmere Reading Order.png",
  "Discworld.jpg",
  "DOOM.jpg",
  "Evangelion Further Reading.png",
  "How Should i read Dune.jpg",
  "Lain Pill.jpg",
  "Snufkin Pill.png",
  "The Big Lez.png",
  "Warhammer 40k - 1.jpg",
  "Warhammer 40k - 2.jpg"
],
"Conspiracy" : [
  "Escape The Matrix.jpg",
  "Fringe.png",
  "Gatekeepers Remorse.jpg",
  "Green Pill Chart.jpg",
  "pizzagate1.jpg",
  "pizzagate2.jpg",
  "Textbooks Of The Elite.png"
],
"Country & Region" : [
  "Brazil & Portugal - Portuguese Language.png",
  "Brazil - 1.jpg",
  "Brazil - 2.jpg",
  "Brazil - Classics.jpg",
  "Brazil - Comtemporanea.png",
  "Brazil - Modernista.png",
  "Brazil - Pos Romanticos.png",
  "Britain.jpg",
  "Canada - Authors.png",
  "Canada - Poetry.png",
  "China 1.jpg",
  "China 2.jpg",
  "Czech Republic.jpg",
  "England 1.jpg",
  "England 2.jpg",
  "France - 1.jpg",
  "France - Forgotten.jpg",
  "France - Renaissance.png",
  "France - Romantism.png",
  "Germany.jpg",
  "Greece.png",
  "Iceland.jpg",
  "India.jpg",
  "Iran.png",
  "Irish.png",
  "Italy - 1.jpg",
  "Italy - 2.jpg",
  "Italy -Renaissance Literature.png",
  "Japan - Woman in Heian and Kamakura Periods.png",
  "Japan 1.jpg",
  "Japan 2.jpg",
  "Japan 3.jpg",
  "Korea.jpg",
  "Latin America - 1.png",
  "Latin America - 2.png",
  "Mexico.jpg",
  "Nederlands.jpg",
  "Norway.png",
  "Persia.jpg",
  "Poland.png",
  "Russia & Poland - Science Fiction.jpg",
  "Russia.jpg",
  "Serbia.png",
  "Spain - Mystic.png",
  "Spain 1.jpg",
  "Spain 2.png",
  "United States - 1.jpg",
  "United States - 2.jpg",
  "United States - American Folklore.jpg",
  "United States - Burgerpunk General.png",
  "United States - Burgerpunk Value Menu.png",
  "Uruguay.jpg"
],
"History, Geography & Antropology" : [
  "Bronze Age.jpg",
  "Germans.jpg",
  "Greeks - 1.jpg",
  "Greeks - 2.jpg",
  "Greeks - 3.jpg",
  "Indo Europeans.jpg",
  "Norse History and Literature.jpg",
  "Romans - 1.jpg",
  "Romans - 2.jpg",
  "Romans - 4.jpg"
],
"Horror, Creepy & Disturbing" : [
  "100 Horror Authors.jpg",
  "Dark and Disturbing Literature.jpg",
  "Gothic and Horror Flowchart.jpg",
  "Horror Fiction 1.jpg",
  "Horror Fiction 2.jpg",
  "Horror Story Collections.png",
  "Post Apocalyptic.jpg",
  "Weird Stories.png",
  "X Board - 1.jpg",
  "X Board - 2.jpg",
  "X Board - 3.png"
],
"K Related & Self Improvment" : [
  "Drawing Books 1.jpg",
  "Drawing Books 2.jpg",
  "Fitchart 1.jpg",
  "Fitchart 2.jpg",
  "Kommando.png",
  "Prep.jpg",
  "The Darre Pill.jpg",
  "Victory Now.jpg",
  "War Literature.jpg"
],
"Literature" : [
  "Absurdism.png",
  "Adventure.png",
  "Arthurian Folklore.png",
  "Book Accessibility Chart.png",
  "CyberPunk.jpg",
  "Cyberpunk.png",
  "Erotic Literature.jpg",
  "Essays.jpg",
  "Fantasy - 1.jpg",
  "Fantasy - 2.jpg",
  "Fantasy - 3.jpg",
  "Gothic.jpg",
  "High Romance.png",
  "Humor.png",
  "My First Novel.png",
  "National Epics.png",
  "Novellas 1.jpg",
  "Novellas 2.jpg",
  "Picaresque Fiction.png",
  "Romance.png",
  "SciFi & Fantasy - 1.png",
  "SciFi & Fantasy - 1996 to 2016.png",
  "SciFi & Fantasy - Modern.jpg",
  "SciFi - 1.jpg",
  "SciFi - 2.jpg",
  "SciFi - 3.jpg",
  "SciFi - 4.jpg",
  "SciFi - 5.jpg",
  "SciFi - 6.jpg",
  "SciFi - Female.jpg",
  "SciFi - Soft Science Fiction.jpg",
  "Short Story - 1.jpg",
  "Short Story - 2.jpg",
  "Theatre & Drama 1.jpg",
  "Theatre & Drama 2.jpg",
  "Web Novels.jpg",
  "Western Literature 1.jpg",
  "Western Literature 2.jpg",
  "Western Theatre.png"
],
"Miscellaneous Knowledge  Fields" : [
  "Biology.png",
  "Biz - 1.png",
  "Biz - 2.jpg",
  "Computer Science - 1.jpg",
  "Computer Science - 2.jpg",
  "Economics.jpg",
  "Learning to invest.png",
  "Math - 1.jpg",
  "Math - 2.png",
  "Math - 3.jpg",
  "Math - 4.jpg",
  "Math - 5.png",
  "Math - 6.png",
  "Math - 7.png",
  "Math - 8.jpg",
  "Math - Curriculum.png",
  "Math - Math and Logic.png",
  "Physics.png",
  "Programming Books.jpg",
  "Psychotherapy.png",
  "Science Literature 1.jpg",
  "Science Literature 2.png",
  "Trivium.png"
],
"Poetry" : [
  "An Introduction to Poetry.png",
  "An Introduction to Verse.jpg",
  "English Poetry Guide.png",
  "Lit Favorite Poets - 1.png",
  "Lit Favorite Poets - 2.png",
  "Poems on Massacres and Hell.jpg",
  "Poetry - Meme Edition.jpg",
  "Roll for Poems.jpg"
],
"Politics, Philosophy & Economics" : [
  "4chan Pol - 1.jpg",
  "4chan Pol - 2.jpg",
  "Analytic Philosophy - 1.png",
  "Analytic Philosophy - 2.jpg",
  "Analytic Philosophy - 3.jpg",
  "Analytic Philosophy - 4.jpg",
  "Analytic Philosophy - 5.jpg",
  "Anarchism - 1.jpg",
  "Anarchism - Post Left Anarchism.png",
  "Anarcho Syndicalistes.jpg",
  "Anarchocapitalism 1.jpg",
  "Anarchocapitalism 2.jpg",
  "AnarchoPrimitivism.jpg",
  "Ancient Western Philosophy.jpg",
  "Anti Work Reading List.png",
  "British Conservatism.jpg",
  "Communalism.png",
  "Deep Ecology.jpg",
  "Distributism.jpg",
  "EcoFascism.png",
  "Economics Education.png",
  "Existentialism.jpg",
  "Facism.jpg",
  "Leftist & Progressive.jpg",
  "Leftist Theory Starter Options.jpg",
  "Legal Philosophy Guide.png",
  "Leninism.jpg",
  "Libertarian.jpg",
  "Marxism 1.png",
  "Marxism 3.jpg",
  "Marxism 3.png",
  "Modern Philosophy 1.jpg",
  "Modern Philosophy 2.jpg",
  "Monarchia 1.jpg",
  "Monarchia 2.jpg",
  "National Communism.jpg",
  "NeoFeudalism.png",
  "Neoliberal.png",
  "PaleoConservatism.png",
  "Philosophy Overview.jpg",
  "Philosophystack.png",
  "Political Philosophy - 1.jpg",
  "Political Philosophy - 2.jpg",
  "Political Theory.jpg",
  "Reactionary Literature.jpg",
  "Rhetoric.jpg",
  "Right Wing Literature.jpg",
  "Right Wing Socialism.png",
  "Scientific Revolution.jpg",
  "Slave Lord Guide.jpg",
  "Stoicism.jpg",
  "Techno Skepticism.png",
  "Third Position Economics.jpg",
  "Traditionalism.jpg",
  "Various Pills.jpg"
],
"Religion & Spirituality" : [
  "Asatru Neopagan.jpg",
  "Bibles Translations.png",
  "Buddhism 1.jpg",
  "Buddhism 2.jpg",
  "Buddhism 3.jpg",
  "Celtic Paganism.png",
  "Chistianity - Poetic Narratives.jpg",
  "Christianity - Breadpill.png",
  "Christianity - Chatolic 1.jpg",
  "Christianity - Chatolic 2.jpg",
  "Christianity - Doctrine.jpg",
  "Christianity - Ecotheology.jpg",
  "Christianity - Ecumenical Councils.jpg",
  "Christianity - Exotericism.png",
  "Christianity - General Reading.png",
  "Christianity - History.jpg",
  "Christianity - Mysticism.jpg",
  "Christianity - Orthodox 1.jpg",
  "Christianity - Orthodox 2 PLUS SCHIZO STUFF.png",
  "Christianity - Orthodox 3.jpg",
  "Christianity - Protestantism.png",
  "Christianity - Puritanism.png",
  "Daoism.jpg",
  "Eastern Mystic Philosophy.png",
  "Esoterica - 1.jpg",
  "Esoterica - 2.jpg",
  "Esoterica - 3.jpg",
  "Esoterica - Brownpilled.jpg",
  "German Paganism.png",
  "Hermeticism.jpg",
  "Hindu Texts.png",
  "Initiation into Hermetics.png",
  "Islam - 1.jpg",
  "Islam - 2.png",
  "Islam - Exoteric Islam.jpg",
  "Medieval Mysticism.png",
  "Quran Translations.jpg",
  "Satanism.png",
  "Western Occultism - 1.png",
  "Western Occultism - 2.png",
  "World Religions Chart.jpg"
],
"Themed Charts" : [
  "Addiction Essentials.jpg",
  "Beowulf.jpg",
  "Blackpilled.png",
  "Bloomer.jpg",
  "Books About Books.png",
  "By Age - Books for Teenage Boys.png",
  "By Age - Patrician Child.png",
  "Depressing Literature.jpg",
  "Doomer & Bloomer.jpg",
  "Doomer.jpg",
  "Drugs - 1.jpg",
  "Drugs - 2.png",
  "Dungeon Synth.png",
  "Dying Earth Core.png",
  "Dystopia & Utopia.jpg",
  "Escaping Society.jpg",
  "Fedora Pill.png",
  "Female - Authors 1.jpg",
  "Female - Authors 2.png",
  "Female - Understanding Women.png",
  "Film Theory.png",
  "Golden Pill.jpg",
  "Great Characters.jpg",
  "Middle Earth.jpg",
  "Nautical.png",
  "Orange Pill - Bitcoin.jpg",
  "Outdoors.png",
  "Paranoia.png",
  "Pessimist.jpg",
  "Pewdiepie Reading List.jpg",
  "Self Published.jpg",
  "Tiger Literature.jpg",
  "Translations.png",
  "Travel Literature.jpg",
  "Tuberculosis Sanatorium Novels.png",
  "Twitter Core.jpg",
  "Utopianism.jpg",
  "Weed.png"
],
"Tops" : [
  "20th Century Lit 1900-1924.jpg",
  "20th Century Lit 1925-1949.jpg",
  "20th Century Lit 1950-1974.jpg",
  "20th Century Lit 1975-1999.jpg",
  "Lit Top 100 Books 2014 - 2017.jpg",
  "Lit Top 100 Books 2018.jpg",
  "Lit Top 100 Books 2019.jpg",
  "Lit Top 100 Books 2020.jpg",
  "Lit Top 100 Books 2021.png",
  "Lit Top 100 Books 2022.jpg",
  "Lit Top 100 Novels 2020.jpg",
  "Lit top 2014 - 2020 avarege.jpeg",
  "Portuguese Language Top 50.png",
  "Top 10 Works of Fiction.png"
]};